### ISSUE TITLE
Question: can it run in background? 

### ISSUE THREAD

**Issue by x4080** [progress/estimote-nativeScript-plugin#1]
Since ns dont support background thread? 

But cool plugin still

**Comment by mehfuzh** [comment]
Beacon monitoring is paused whenever the app goes background. Also, please check this out from estimote community:
[https://community.estimote.com/hc/en-us/articles/203914068-Is-it-possible-to-use-beacon-ranging-in-the-background-](https://community.estimote.com/hc/en-us/articles/203914068-Is-it-possible-to-use-beacon-ranging-in-the-background-)

Thanks!

**Comment by x4080** [comment]
Thanka

**Comment by valentinstoychev** [comment]
Can we use the solution @Nathanaela created for brackground processing? https://www.npmjs.com/package/nativescript-webworkers

**Comment by NathanaelA** [comment]
@valentinstoychev,

No, unfortunately what I developed can't run any NS code/plugins.  It can only run straight JS code.  :-(

**Comment by toddanglin** [comment]
This is far from my area of technical expertise, but could NativeScript apps could respond to beacon events triggered by iOS, even when in the background or killed? Perhaps similar to solution described here: https://community.estimote.com/hc/en-us/articles/203253193-Pushing-notifications-from-iBeacon-when-the-app-is-in-the-background-or-killed

Apps get 10 seconds to process after a beacon event is triggered. 

Or does NativeScript still need to add explicit support for background processing in iOS for this work?
